### PR TITLE
Add pushbullet channels; Add auto-migrate database feature

### PR DESCRIPTION
**Pull request by rigrassm**
I re worked my original pull request to address the issue with current users upgrading. With this update, current users can update to the latest codebase without losing the data that already have in their databases.

To test this I setup and configured an instance of the current version in your repo and tested to make sure everything worked. I then created a patch file against the version with my changes using diff. While PlexRequests was still running, I applied the patch directly to the app directory which applied all the changes. The server restarted itself and immediately patched its database once it registered the updated schema. From there everything worked as expected and the new pushbullet option was available and tested successfully.

### CODE REVIEW

**Comment by lokenx** [comment]
Awesome, I'll give it a few tests this weekend and merge if all goes well!

**Comment by rigrassm** [comment]
Sounds good, message me if you have any questions.

**Comment by lokenx** [comment]
Seems good so far, update the version to 1.7.0 in the version.txt and [here](https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/admin/version.js#L6) before merging.

**Comment by rigrassm** [comment]
Version updated in both places to 1.7.0

**Pull request merged**
