### PR TITLE
pulling in total number of episodes

### PR DESCRIPTION
**Pull request by forkwhilefork**

### CODE REVIEW

**Comment by lokenx** [comment]
This gets added when it talks to Sonarr/SickRage but this works too for a bit quicker info. See other PR first then I'll test this.

**Comment by forkwhilefork** [comment]
the problem with that is I don't use Sonarr or SickRage, so they all show up as 0/0 for me. I'm not 100% convinced this works though, I might have been a bit eager >.>

**Comment by lokenx** [comment]
Well with this they'd show up as `0/X`, X being the total number of episodes. Is that better?

The idea is to integrate into Plex to get numbers from there.

**Comment by forkwhilefork** [comment]
Yeah, I figured one 0 was better than two 0's. Does Plex have a way to provide the total number of episodes? Because if so then it would probably be better to pull both numbers from there.

**Comment by lokenx** [comment]
So did some tests and that field, `number_of_episodes`, doesn't get returned in search results, so it's always 0.

**Comment by forkwhilefork** [comment]
I just noticed the same thing. It shows up when you do a query with the id of the show, but I guess not when you search.

**Comment by forkwhilefork** [comment]
You could take the id returned by the search and make a request with that, but then you're doubling the number of requests. Maybe it would be better to just pull all of the info from Plex?

**Comment by lokenx** [comment]
The API docs are available [here](http://docs.themoviedb.apiary.io/).

It's available with an individual show ([here](http://docs.themoviedb.apiary.io/#reference/tv)) but not with searches ([here](http://docs.themoviedb.apiary.io/#reference/search/searchtv))

**Pull request closed without merging**
