### PR TITLE
Add Extra Movie Search Button

### PR DESCRIPTION
**Pull request by nbyloff**
I used the .NET version for Plex Requests for a while before switching to this version. A convenient feature it had was a drop down box that allows you to auto search for movies currently in the theaters as well as due to be released soon. This adds that feature here as well. A reusable function could be made, but otherwise it's a very minor but useful addition.

### CODE REVIEW

**Comment by jeradM** [comment]
Very nice. I just started using plexrequests a couple of days ago and was considering adding this since it is a cool feature in OMBI, so I'm glad to see someone has already worked on it. I've been testing this and it is working great, my only suggestion is to use the `now_playing` API endpoint rather than `discover` for the "In Theaters" search  since it seems to return a more accurate list of in-theater movies.

**Comment by nbyloff** [comment]
Good catch, didn't see that endpoint; just took the first one I found. I also forgot to hide the button when clicking on the TV Shows tab, so that has been fixed. 

Happy I found this version of plexrequests; works great on my NAS.

**Comment by nbyloff** [comment]
Any chance of this getting merged?

**Comment by rigrassm** [comment]
Apologies for the delay.

Definitely want to get this merged, let me get the dev-testing branch rebased to the current master here in a little bit and once that's done I'll have you submit the pull request against that branch. Still have some kinks to iron out after the Radarr integration that need to be addressed before adding any new features into Master.

**Comment by rigrassm** [comment]
Ok, please resubmit the pull request against dev-testing and I'll get it merged.

**Comment by nbyloff** [comment]
Done. Thanks!

**Comment by nbyloff** [comment]
Any chance this can get merged? This feature was really helpful.

**Comment by lokenx** [comment]
@rigrassm question, I haven't touched `dev-testing` and not sure what he's doing in there! If there's no reason to go into there first I can merge straight to master 👍

**Comment by lokenx** [comment]
@nbyloff switch back to master and I'll merge 👍

**Comment by nbyloff** [comment]
@lokenx done. And thanks! I use the synology version and they merge this repo for new versions. Wanted to add this feature to my NAS. 👍

**Pull request merged**
