### PR TITLE
Added option to use a Pushbullet Channel Tag

### PR DESCRIPTION
**Pull request by rigrassm**
I wanted to be able to have Pushbullet notifications be sent to multiple users so that they too could get updates on when content gets requested/approved and ultimately added to PleX (by utilizing the Pushbullet settings in both Sonarr and CouchPotato you can easily setup a solid distributed notification system). So I dug in and made a few changes to add this functionality and it seems to work great.

As of now you can only send to one channel but I will adding the ability to send to multiple channels soon.  I also plan on rounding it out by adding the ability to limit sending notifications to individual devices based on registered device ID's.

### CODE REVIEW

**Comment by lokenx** [comment]
Awesome feature! You just need to determine how to handle one specific use case: existing users.

Settings only get generated once, if there are none. Because of this any existing users of the app wont  have this new setting field and it won't get added by itself. When they use Pushbullet to send a notification it'll error out as that field isn't defined and an alternative isn't provided.

**Comment by rigrassm** [comment]
Thanks for pointing that out, this is my first time working with meteor and mongo and I didn't realize that changing the schema would have that effect.

That got me thinking and after a bit of searching I found a package designed specifically for remedying this situation. The package is valued collection2-migration; it's designed to monitor the schema of a projects database for changes and when it detects any it then goes through and updates the old entries of the collection to reflect the change.

I tested the packages functionality by installing and configuring a fresh instance of PlexRequests and then applied the changes to it while it was still running. The package did exactly what it said it would and immediately recognized a change in the settings collection schema. It then updated the collection in real time and the new functionality was working as expected after refreshing the browser!

With the hard part out of the way, I added a bit of logic to the test Notifications code that checks if a channel is set and adjusts the parameters of the http.post function accordingly. Before this it was failing silently if the channel was left blank and now it works just as you would expect. If an incorrect channel_tag is given or the channel isn't owned by the user trying to push to it, it will throw an error when the test is run.

I'm gonna clean up the code a bit today and resubmit a new pull request.

**Comment by rigrassm** [comment]
Just to clarify a bit about the migration process. It's my understanding that users can back up their database from their current install and migrate it over to the new version. So long as this is the case, the application should recognize that there was a change in the schema and update the collection to reflect the change when the application starts.

The best part about this implementation is that since it monitors each collection in the database, users are able to update the application without losing their data or having to go through a complicated update process.

**Comment by rigrassm** [comment]
Resubmitted new pull request. Request #278

**Pull request closed without merging**
