### PR TITLE
Testing custom notifications

### PR DESCRIPTION
**Pull request by rigrassm**
Please merge and test the custom notifications functionality. I haven't documented it yet but basically it lets you create dynamic notification content using `<tags>` as placeholders for various values related to the requested media. See server/methods/admin/serviceTests.js for the tags that have been implemented so far.

Its pretty straight forward and seems to work pretty well for something that was thrown together in a couple hours. The basic syntax is like so:

Custom Title: `Plex <type>`
Custom Body: `<user> has requested <title> (<year>)`

Output:
`Plex request`
`test_user has requested A Good Movie (2016)`

In theory, users should be able to utilize slacks special formatting directly in the text and have it show up correctly when the message appears. Let me know if you find any bugs, i'm going to work on cleaning it up and making it a bit more streamlined this weekend.

### CODE REVIEW

**Comment by lokenx** [comment]
You want to merge to master or dev?

**Comment by rigrassm** [comment]
Figured since its a little rough around the edges you could merge it with
dev and then if it checked out merge into the master.

**Comment by lokenx** [comment]
OK, but the request is to master not dev. 

image

**Comment by rigrassm** [comment]
Oh, I don't know why this pull request is open. Going to cancel it.

**Pull request closed without merging**
