### PR TITLE
TVMaze Integration, Custom Notifications and Code Cleanup

### PR DESCRIPTION
**Pull request by rigrassm**
## Custom Notifications

Users are now able to set custom notification messages!
The message consists of two parts, a title and the message body.
Messages support variable substitution allowing the user to produce
dynamic message content. The following are a few of the variables available:
* `<title>` - Title of the requested Movie/TV Show
* `<year>` - Year the requested media was rekeased
* `<link>` - URL to the requested medias information page
* `<user>` - Username of the user requesting the media
* `<type>` - Type of media being requested, returns movie or tv

## TVMaze Support

PlexRequests now retrieves its TV show information from the TVMaze.com
database. Utilizing TVMaze as a dedicated TV database provider will offer:

* A larger database to search against making it more likely the user
will find the series they are searching for
* More accurate and in-depth metadata
* More forgiving search funtionality that will return results even if
there are slight spelling errors.
* Ability to add new features thanks to the comprehensive amount of data
TVMaze is able to provide

Head over to [TVMaze.com](http://tvmaze.com) information about their service
or to learn more about their API,
visit [tvmaze.com/api](http://tvmaze.com/api).

### CODE REVIEW

**Comment by whitecollar17** [comment]
Good job!

**Comment by tidusjar** [comment]
Why use TVMaze over TheTvDb?

**Comment by rigrassm** [comment]
Two reasons

1) TVMaze's API was much cleaner and more refined than TVDB's(In my opinion)
2) TVMaze has an open API that doesn't require an API key to use the service.

**Comment by rigrassm** [comment]
I'm especially glad I went with them and dont have to use an API key after what just happened with CouchPotatoand TMDB. The CP api token was revoked for some reason and hasn't been working at least for the last week.

**Comment by tidusjar** [comment]
Yes I agree, not using an API key is a massive bonus. I'm going to switch my version of PlexRequests over to TVMaze now.

**Comment by lokenx** [comment]
There had to be conflicts eh?! Haha I'll get started on this tonight/tomorrow evening :+1:

**Comment by tidusjar** [comment]
Interestingly i'm just testing out TVMaze with my version and it seems to be a lot faster than TheTvDb

**Comment by rigrassm** [comment]
I'm really surprised how relatively unknown TVMaze actually is. I haven't found a reason touse TVDB over it yet.

**Comment by rigrassm** [comment]
@lokenx if you want me to I can work out those conflicts, it doesn't look like there will be anything too major to deal with.

**Pull request merged**
