### PR TITLE
Notification refactoring

### PR DESCRIPTION
**Pull request by leonkunert**
I refactored the notification system, so the duplicate implementation for sending notifications is gone.
I'm not sure about the default values for the notification provider urls because I had to remove my .meteor folder to get correct values.

### CODE REVIEW

**Comment by lokenx** [comment]
Which URL's you referring to exactly?

**Comment by leonkunert** [comment]
Oh sorry. The pushbulletURL and the pushoverURL I added to the settings.

**Comment by lokenx** [comment]
I think you have the correct ones [here](https://github.com/lokenx/plexrequests-meteor/pull/268/files#diff-10952e1477bba05d707e90182bd04d3bR327) and [here](https://github.com/lokenx/plexrequests-meteor/pull/268/files#diff-10952e1477bba05d707e90182bd04d3bR355). Why you putting the URL's in there, is there any reason for them to be changeable?

**Comment by leonkunert** [comment]
I thought about testability, that would be easier if everything is configurable.

**Comment by lokenx** [comment]
OK. You need to find a way to either provide a default for those new values, or a way to add them to existing databases. Settings get created on first run, but if someone already is running the app and upgrades, their PushBullet/Over notifications would now fail as they don't have the new settings URL in their DB.

**Comment by leonkunert** [comment]
I moved them to the files now and removed the configs. Thats not very nice, but it will work. I will open a new ticket to fix that. For now I think I'm done here. @lokenx ready to merge??

**Comment by lokenx** [comment]
Up the version as before, and merge @leonkunert , you should be able to as a contributor.

**Pull request merged**
