### PR TITLE
Added the Plex User Name to the PushBullet notification

### PR DESCRIPTION
**Pull request by hthighway**
If plex is enabled notification will read "Plex Request By JoeSmith"  otherwise it will read as before

### CODE REVIEW

**Comment by hthighway** [comment]
I just saw in the forum you were already working on this type of feautre so you can disregard this pull request 

"I'm not sure how you're getting the requesters name? Are you adding their name into the Settings collection under plexuser when they authenticate and then calling that variable on the push bullet notification?"

And yes that is how it is happening

**Comment by hthighway** [comment]
"We'll be adding the requesters name to the movie entry itself, and then pulling it from there."

That is the best way, and I looked a that but it was more involved than the time I had available so I grabbed it from plexuser when they authenticated

**Comment by Jeradin** [comment]
Hello @hthighway 
I added a pull request which deals does this now.
https://github.com/lokenx/plexrequests-meteor/pull/37

The branch is here: https://github.com/Jeradin/plexrequests-meteor/tree/add-user-notification

Can you test the PushBullet title?

**Comment by lokenx** [comment]
Closing this PR, please refer to #37

**Pull request closed without merging**
