### PR TITLE
Add missing loading template

### PR DESCRIPTION
**Pull request by Jeradin**
Add missing template when loading the admin section.

### CODE REVIEW

**Comment by lokenx** [comment]
I noticed that too, I think it's a problem with the [houston:admin](https://github.com/gterrono/houston) package but haven't had time to research it. I've also just deprecated sacha:spin in favour of simpler CSS spinners in the dev channel. Also, your file extension is .php which I'm assuming is a miss type?

**Comment by Jeradin** [comment]
Oops! foolish me, so used to working with PHP... Yes it was meant to be html extension which got rid of the error on my test server.

Use a CSS based spinner sounds like a good plan!

**Comment by lokenx** [comment]
No worries, currently the loading template is gone for me so not sure what is up. But even weirder, when I remove sacha:spin my routes break yet admin ones work fine...not sure what's happening!

**Comment by lokenx** [comment]
Added as of commit 1144c1d92940a6dc0230253393b685366151c355 in dev with new CSS spinner instead of sacha:spin

**Pull request closed without merging**
