### PR TITLE
Select Sonarr profile from list

### LINKED ISSUE #190: Diffcult to config Sonarr in plex requests
Its very difficult to find the correct "Download quality profile ID". When you use a wrong ID, the serie add it in sonarr, but sonarr can't do anything because there is no quality profile linked to the serie.
You can't find it in sonarr, unless you do a try and error in plex request. I try to add 7 times a serie and change my profile id with +1 every time.
After eight times i found out my ID was 8.
is it possible to make a change in the admin panel that you can select the names of your quality profile instead of giving the ID (wat very hard and difficult to find?)

Also you can use a wrong or  invalid/ not existing ID and you get a sonarr error.
(It is a bug in sonarr also: https://github.com/Sonarr/Sonarr/issues/977 )

### PR DESCRIPTION
**Pull request by Dahlgren**
TODO
- [ ] Don't request Sonarr profiles if Sonarr is not enabled
- [ ] Refresh Profiles list on Sonarr settings updated
- [ ] Preselect first?

Fixes #190

Requires https://github.com/lokenx/sonarrwrapper/pull/1

Any feedback is welcome, not that experienced in Meteor

### CODE REVIEW

**Comment by lokenx** [comment]
Shall have a look in new year. Hopefully code isn't too Meteor specific and can be moved to new backend (Hapi/Nodejs)

**Comment by whitecollar17** [comment]
nice :)

**Comment by whitecollar17** [comment]
@lokenx  , is this Merged to soon? He was still busy with fixing "Don't request Sonarr profiles if Sonarr is not enabled" , " Refresh Profiles list on Sonarr settings updated" and "Preselect first?"

**Comment by lokenx** [comment]
It still worked, those just seemed quality of life improvements. If there’s any reports of major issues I’ll roll back without issue.

If you don’t think let me know and I’ll roll back today.

**Comment by whitecollar17** [comment]
I think this pr incomplete, see problem 234: https://github.com/lokenx/plexrequests-meteor/issues/234

**Comment by whitecollar17** [comment]
I think this pr is incomplete, see problem https://github.com/lokenx/plexrequests-meteor/issues/234
I propose to rollback and wait for @Dahlgren

**Comment by Foebik** [comment]
Yeah, It's not pulling the profiles for me.

**Comment by Dahlgren** [comment]
Yep, that other PR on sonarrwrapper is needed

**Comment by lokenx** [comment]
My bad, I had it merged locally hence it worked for me. A restart should update the Sonarr package and then this should work for everyone else.

**Comment by geekjoe02** [comment]
Not sure if this is the right place to post this but I will give it a shot.  I just started working with plex requests yesterday.. I have couch potato all setup and its working great.  I am having issues with sonarr and I am not sure what I am doing wrong.  What I think is happening is the profiles arent pulling in so that when it goes to request and add a new show it errors out because plex requests cant pass the data along.

Let me know if that is right and if there is a fix happening.  

thanks for the work here this is an awesome project.

**Comment by lokenx** [comment]
Please update the app or a restart should do it. It needs to get the new package version that's all. If a restart doesn't work just do a git update from the master branch as it has the new version added just now.

**Comment by geekjoe02** [comment]
Just did an update from GIT and restarted.  Still no drop down on the Select Quality profile in the Sonarr tab.. Im pretty sure this is the issue as to why it isnt working with Sonarr but im not 100%.

**Comment by lokenx** [comment]
Can you try the below thing, and yeah you're not getting the update.

https://github.com/lokenx/plexrequests-meteor/issues/236#issuecomment-172701915

**Pull request merged**
