### PR TITLE
Added a denied option for requests

### PR DESCRIPTION
**Pull request by Qw-in**
A response to issue #361: Just a quick deny option for requests. Curious about the best way to get the string for the denied message.

### CODE REVIEW

**Comment by lokenx** [comment]
Great work! Just a thought, still have to handle existing shows that are `true` or `false`. For example [this](https://github.com/lokenx/plexrequests-meteor/blob/master/server/methods/admin/updateDB.js) is for when we started showing season count.

Also the DB schema is currently invalid now (see [here](https://github.com/lokenx/plexrequests-meteor/blob/master/lib/collections/collections.js#L47) and [here](https://github.com/lokenx/plexrequests-meteor/blob/master/lib/collections/collections.js#L105)), it shouldn't have let you create new entries with the current setup.

**Comment by Qw-in** [comment]
I was hoping that since I replaced `true`/`false` with `1`/`0` that it would be backwards compatible, since javascript seems to treat them the same. I'll have to test on an old database.

Should I create a new database entry instead of changing `approved`? Or can I update it somehow?

Thoughts on getting text entry? I was thinking maybe a popup that appears after `Deny` / `Deny All` is pressed, similar to the welcome screen.

**Comment by lokenx** [comment]
That is true, but shall test to confirm.

You can adjust the schema, a migration will happen--old entries will be left unchanged and new ones will adhere to the new schema. But shall confirm to make sure.

Yeah, you could do a modal window or even simpler just a text input field/box. Clicking the denied button doesn't do anything, it merely opens the modal that has the text entry and buttons to make the calls and such.

**Comment by rigrassm** [comment]
Will confirm, old entries will actually be updated by the migration tool to
make them compliant with the new schema. In our case, they were getting
deleted before so you would be safe to script out a query to update all the
entries to approved the first time the app is run after updating.

See the updateDB.js file for a template if you need an idea of how to
handle it.

**Comment by Qw-in** [comment]
OK, so I tried to handle it similarly to what is found in updateDB.js but because I am changing the type of the `approved` entry I get errors from plugins before settings.js is even run. So, as a work around I am planning to leave 'approved' as bool and create a new 'status' entry. 'approved' will be depreciated and could eventually be removed.

**Comment by lokenx** [comment]
So everything seems good! I just found a bug that's related to the other PR for per user permissions and such. If someone isn't using Plex users, no one can request things as it fails to find the user whose making the request and errors out.

Will have to look and see how best to handle that, and whether to add before or after this PR.

**Comment by rigrassm** [comment]
Aside from that I haven't found anything either yet.

About the bug, is it when they require plex authentication and or when they
don't?

**Comment by Qw-in** [comment]
Oh! Good catch! I think I know what the issue is and will add a separate PR asap.

I'm still trying to find a method of taking user input (for deny request) that feels like it fits the UI. Currently considering a dropdown (similar to `report issue`) or a popup. Having a text box appear just felt clunky, especially on mobile.

**Comment by lokenx** [comment]
I don't think ther s anything wrong with a modal type window? However I like the drop down idea too, whichever works really!

**Comment by Qw-in** [comment]
I have been working from the master branch of my fork, and because of that I don't think I am able to create a separate PR. Lesson learned. If you wanted to merge this it is in a working state (just have to implement the text box separately later) or commit 3d5c4ec fixes the bug.

**Comment by lokenx** [comment]
What about leaving 'Deny' as an option even if you've approved it. Same logic applies that you keep the 'Approve' button after you've already denied something?

Add something like the below as well to clear the reason field 

```$('#denyModelReason').val('');```

Also, update the version to `1.15.0` in `version.txt` and `server/methods/admin/version.js` so can merge

**Comment by Qw-in** [comment]
Correct me if I'm wrong but once something is approved isn't it sent to couchpotato / sickrage / sonnar? Would `deny` just update the UI or actually remove the item via the APIs?

**Comment by lokenx** [comment]
Nope you are correct, I never wanted to hock into the downloaders to remove things as it just seemed messy--so yeah makes sense as is.

**Comment by lokenx** [comment]
Shit sorry man, didn't get notification for this--I think email notifications are broken or something.

I'll check and merge ASAP!

**Pull request merged**
