### PR TITLE
Added ability to read downloaded status from Radarr

### PR DESCRIPTION
**Pull request by ohmar**
This is to resolve issue #452. I tested it on my own installation with great results. Not sure if there are certain guidelines to follow but I tried to implement this as a hybrid of CouchPotato and Sonarr. Please take a look and let me know what you think.

### CODE REVIEW

**Comment by rigrassm** [comment]
Let me look at this a bit, I actually started reworking download status to
be a single method that will spur a check to the enabled clients and return
a unified response. I was about to start working on Radarr so I may
integrate your check rather than reinvent the wheel.

**Comment by ohmar** [comment]
For some reason my formatting makes it seem like I changed much more than I really did. Here are the main changes; added radarrMovieStatus, updated updadeRadarr and updated cronjobs.

**Comment by rigrassm** [comment]
Awesome, I'll probably be working on it tonight or tomorrow.

**Comment by ohmar** [comment]
Any updates on this?

**Comment by rigrassm** [comment]
Sorry for the delay, I haven't been able to dive into this like I wanted to so I will be merging this into dev-testing as is since it looks good to go as is.

**Comment by schott1984** [comment]
I understand that "available" status from radarr is not currently working, right? Just making sure because mine is not. Want to be sure I don't have something set wrong on my end.

Running radarr and plexrequests via the unraid docker containers.

**Comment by ohmar** [comment]
Available status from Radarr is working in dev-testing but not master.

**Pull request merged**
