### PR TITLE
Add IFTTT Maker Support. 

### PR DESCRIPTION
**Pull request by rigrassm**
Add the ability to trigger events on IFTTT using the services "Maker" Channel. The web requests sent to IFTTT can take up to 3 seperate fields of data(Value1,2&3) and is setup to use the same variable tags that are available to the custom notifications.

[IFTTT Maker](https://ifttt.com)
=========================

[IFTTT](https://ifttt.com) stands for " IF THIS, THEN THAT". The service allows you to observe one service and have an action taken by another service based on some defined criteria. The key to using the service with PlexRequests is by utilizing the **"Maker Channel"** which accepts a web request and up to 3 value fields that it passes on to whatever 3rd party service you choose to connect it to. 

When a notification is sent out from PlexRequests, it sends the values you defined in the admin settings panel to a specified "Channel Name"(similar to Pushbullet channels) that you have defined with IFTTT. From there you can create "Recipes" that get executed every time data is received on that channel.

For example:  

> I have a channel called "plex_request" created on [IFTTT](https://ifttt.com), the following are recipes that are executed upon [IFTTT](https://ifttt.com) getting a request on that channel with my API token.
> 
> 1. Send me an SMS message with the contents of Value1 and Value 2 in it. 
> 
> 2. Recipe that inserts the value from the Value3(Which I've set to be the title and year of the requested media) into a google sheets spreadsheet hosted on google drive.
> 

These are very simple examples of what can be done, there are countless different things you are able to connect with and do simply by building the recipe on [IFTTT](https://ifttt.com).

You can read more about the ["Maker Channel" here.](https://ifttt.com/maker)

### CODE REVIEW

**Comment by lokenx** [comment]
I didn't see anything that stood out but @stohle let us know what happened with yours? @rigrassm don't forget to bump the minor version number too.

**Comment by rigrassm** [comment]
Yeah, I haven't had anything happen either but that's only using Linux as I
don't have a Windows install to test on(though it shouldn't have any
effect).

**Comment by stohle** [comment]
Sorry for the late reply @rigrassm

Im starting it with "screen -S plexrequests meteor --port 24472". I have also tried cd in to the directory and just running "meteor" both methods gave me this output here: http://pastebin.com/tWM8axXP

**Comment by rigrassm** [comment]
@stohle: Ahh, looks like when you pulled the new code it left behind some
cached stuff. I reorganized much of the admin methods into one file and it
looks as if Meteor is seeing both the new file and an old one that has the
same setTestVars method in it.

1. Backup your .meteor/local/db folder
2. Execute `meteor reset`
3. Execute `git pull origin master`
4. Execute `git checkout origin/ifttt-maker-enhanced` (note: double check
the branch's exact name, don't have it in front of me ATM)
5. Execute `meteor --port <portnumber>`

See if that fixes it for you and let me know.

**Comment by rigrassm** [comment]
@lokenx: We should look into providing recommended upgrade instructions some where. Most issues seem to stem from stuff getting left behind in meteors cache.

**Comment by stohle** [comment]
@rigrassm it worked! thanks

**Comment by lokenx** [comment]
@stohle what did you do originally to try the branch out that ended up with that error? Just thinking maybe the refactor @rigrassm wasn't part of the branch or there was some git overlap/confusion that caused you to have a slightly different state.

@rigrassm Yeah something like what you posted above in the Wiki would work!

**Comment by stohle** [comment]
I downloaded the zip to my computer, unzipped and copied over to my server

**Comment by lokenx** [comment]
@stohle ah yeah...that will definitely break nearly every time! You should preferably be using git to keep things in sync and updated. That would will cause issues as you found if we change files/directory structure as you'd have duplicate/overlapping things.

**Comment by lokenx** [comment]
@rigrassm can merge once do a minor version bump I think

**Comment by rigrassm** [comment]
@lokenx Bumped to 1.12.0 and merged

**Comment by lokenx** [comment]
@rigrassm can you also tag a release so the notes show up the about page in the app?

**Comment by cwhitlow101** [comment]
Hello, where exactly is the ability to add IFTTT Maker Channel? I didn't see in the Admin settings under Notifications. Also, would this notify all users, whose number I added into IFTTT, of every request or just the individual who requested it?

**Comment by rigrassm** [comment]
Ifttt maker can do pretty much whatever you want it to with a little work.
It's a webhook that you can use to trigger just about anything and pass
along data with it. You can create multiple recipes in ifttt that get
triggered by the same maker tag getting activated. A basic way to have an
SMS sent to people would be to install ifttt on your phone and create a
recipe to send a text to a specified group of users when it's triggered.

If you have any programming experience you can write a phone script that
could parse the data sent to it in the maker channel payload and perform
different actions based on the content. You could grab the name of the
requesting user and have a notification sent to just that user; check the
request type and send out a notification to a set group of users etc. This
pairs well with push bullet channels as it would allow you to create
multiple channels and send notifications to just the users subscribed to
that particular one.

**Comment by mzaur** [comment]
Hey guys,

I am trying to get IFTTT maker to work with Plexrequests for notifications. Pushbullet works, but I cannot specify device ID (created a ticket for that feature request). I just want notifications to my phone so figured I'd try IFTTT. It works for notifications, but I do not receive any info like what movie was requested and from who, like with Pushbullet. Is it possible to pass along that info? I do see IFTTT Value 1, etc. but not sure what to put there

**Comment by rigrassm** [comment]
You'll want to lookup the API specifications for IFTTT maker. They show you
how to access the data passed in via the 3 value fields so they are
included in your "That" action.

Off the top of my head, I believe you use variables like

    {value 1}{value 2}{value 3}

In the body of the action you created.

On the Plexrequests​ side, you can fill in those 3 fields with whatever you
want including the variable replacement tags.

Hope that helps.

**Comment by mzaur** [comment]
Thanks! I deleted my post because I figured it out :) In IFTTT you add an "ingredient" and there's value 1, etc. so I added <type> <title> requested by <user> and this works!

**Pull request merged**
