### PR TITLE
Feature clear search on Focus

### PR DESCRIPTION
**Pull request by Jeradin**
I was adding lots of movies with my girlfriend last night on my iPhone (which this app you created is faster than the mobile couchpotato!) and I kept needing to delete the last search which was annoying.

I added some javascript to clear the search on field focus.

I polled some other people on best practices:
1. Clear field on focus
2. Add a clear field X option
3. Leave as is

All thought a focus clear was best, some wanted the previous search to be semi saved in a div below to be clicked and populate the field incase they just wanted to correct the result but that seemed like a lot of needless work.

I also considered checking the results:
1. If search replied with "no results" don't clear field, let user edit it.
2. If search, but not requested yet don't clear field, let user edit it.
3. else clear results

### CODE REVIEW

**Comment by lokenx** [comment]
How about a compromise:

    $(document).ready(function () {
            $('#search').focus(function() {
                if($(this).val() != '')
                    $(this).select();
            });
        });

This way if you want to make an edit the previous entry is still there, but if you want to add something new you can just start typing and it writes over.

**Comment by Jeradin** [comment]
Nice! we do need to change .focus to .click to make select work though!
``
$(document).ready(function () {
        $('#search').focus(function() {
            if($(this).val() != '')
                $(this).select();
        });
    });
``

**Comment by lokenx** [comment]
Can you test to confirm? It was working fine for me with focus (OS X Chrome). Plus if it's not focus then pressing the buttons that regain focus wouldn't work.

**Comment by Jeradin** [comment]
I tested again (OS X Chrome also) when it is set to focus and I click in the field it selects for a millisecond and than the cursor goes to the end of the search term. It is a bug reported for Chrome (some versions [link](http://stackoverflow.com/questions/3380458/looking-for-a-better-workaround-to-chrome-select-on-focus-bug) ) This solution works for me for chrome desktop, but not iOS chrome/Safari for some reason. 

```
    <script>
	    $(document).ready(function () {
			$('#search').focus(function () {
			    $('#search').select().mouseup(function (e) {
			        e.preventDefault();
			        $(this).unbind("mouseup");
			    });
			});
	    });
    </script>
```

iOS still researching, people mentioned using  this.setSelectionRange(0, 9999); and also setTimeout but neither solution worked for me.

**Comment by lokenx** [comment]
Ah I only tested using the buttons, not manually selecting the field. What if we do the auto select using the buttons (which works correct?) and then adding an "x" or something to clear manually?

**Comment by Jeradin** [comment]
The above code works for all browsers, I will do some more trouble shooting for iOS/Android. might be nice to avoid an "x" close.

**Pull request closed without merging**
